---
title: "First Knit"
author: "Marbella"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare English class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I attended high school at Rosamond High School. I graduated 2014. English is an easy class to pass.  Math can as well be easy if you put in the work. I enjoy accounting. I like figuring out problems like solving puzzle pieces.   

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
 I have an apple laptop and I know how to use it from scale 1-10, will be 6. I have not used my apple laptop since back in 2018. I will use another laptop that is not an apple and it is a lot different. I have internet access at home and the internet connection is strong. 
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  My name is Marbella and my classmates and professor calls me by my actual name. My friends and family call me Bella for short. I like to be called either or and whatever their preference is.
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
 I want to obtain an associated degree in accounting and business administration. Accounting will be my most interest subject in college and will be graduating with an associates degree in 2024.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
 I have not traveled to foreign countries but I am planning to once I have everything settled in life and make great money to afford to travel. I for sure will love to visit Barcelona.  
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
 I haven't taken either. This will be my first time to taking statistics. I need to take statistics as part of my G.E to graduate in the Spring of 2024.  
   
 






  




